### ISSUE TITLE
Add note about authentication password in the doc

### ISSUE THREAD

**Issue by atefBB** [dunglas/php-torcontrol#13]
Hi @dunglas.
When using `password authentication` while controlling TOR, the auth password must be generated using the command:
`~> tor --hash-password "random_password"`
which will generate a `hashed password` beginning with `16:DEE07A96....` (just an example).
So To control tor the php code must be : 
```php
$tc = new TorControl\TorControl(
                array(
                    'hostname'   => 'localhost',
                    'port'       => 9051,
                    'password'   => '16:DEE07A96A....',
                    // the generated password
                    'authmethod' => 1,
                )
            );
````
I think this trick must be mentioned in the  `README` file.

**Comment by dunglas** [comment]
Would you mind opening a Pull Request?

**Comment by atefBB** [comment]
I'll do when I have TIME !

**Comment by atefBB** [comment]
I have been wrong about this issue! See details https://github.com/dunglas/php-torcontrol/pull/14
