### ISSUE TITLE
Error 10061 - No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by pctin** [dunglas/php-torcontrol#5]
I have config TOR in linux with the following information:
tor --RunAsDaemon 1 --CookieAuthentication 0 --HashedControlPassword "xxx" --ControlPort 8541 --PidFile tor10.pid --SocksPort 40612 --DataDirectory data2/new/tor10 --SOCKSListenAddress 0.0.0.0:40612 --ControlListenAddress 10.220.83.32:8541

I have tested with other machine (10.220.83.24): nc 10.220.83.32 8541, and it's OK.

But when I using this extension in PHP, i got the error:
exception 'TorControl\Exception\IOError' with message '10061 - No connection could be made because the target machine actively refused it.
' in my_web_path\vendors\TorControl\TorControl.php:176

**Comment by dunglas** [comment]
It looks more like a problem in the network configuration than a PHP problem.

**Comment by pctin** [comment]
No, not about network problem.

I see problem is in your example:
$tc = new TorControl\TorControl(
    array(
        'server' => 'localhost',
        'port'   => 9051,
        'password' => 'MySecr3tPassw0rd',
        'authmethod' => 1
    )
);

But at src/TorControl.php, function connect:
$this->socket = @fsockopen($this->options['hostname'], $this->options['port'], $errno, $errstr, $this->options['timeout']);

It has confused about 'server' and 'hostname'.
I have changed to: 
$tc = new TorControl\TorControl(
    array(
        'hostname' => 'localhost',
        'port'   => 9051,
        'password' => 'MySecr3tPassw0rd',
        'authmethod' => 1
    )
);
and I works fine.

**Comment by dunglas** [comment]
Ok so it's a doc problem :) Thank you I'll update the doc.

**Comment by itsazzad** [comment]
Have you updated the doc?
I am also having an error

**Comment by meitar** [comment]
I believe this can be considered closed as of 10d5627928e46e4d2897d8dc2bd80cd13dec7e68.
