### ISSUE TITLE
Requesting multi-line replies caused premature `ProtocolError` exception

### ISSUE THREAD

**Issue by meitar** [dunglas/php-torcontrol#7]
* **This issue is reproducible.**

# Overview

In some cases, Tor responds with data that spans multiple lines. It signifies this with a `+` as per section 2.2 of the Tor control spec:

> A command is either a single line containing a Keyword and arguments, or a multiline command whose initial keyword begins with +, and whose data section ends with a single "." on a line of its own.

Further, in section 2.3 of the spec:

> Multiple lines in a single reply from Tor to the controller are guaranteed to share the same status code.

One such command that you can issue to Tor to get a multi-line reply is the `GETINFO config-text` command.

`php-torcontrol` cannot handle such replies, prematurely throwing a `ProtocolError` on the second line of the response of a multi-line response.

# Steps to reproduce

1. Set up a Tor whose configuration file (`torrc`) contains more than single configuration line.
1. Start Tor.
1. Connect `php-torcontrol` to that Tor server.
1. Issue the `GETINFO config-text` command.
1. Observe premature error.

Code example to perform the above:

```php
function get_tor_config_text () {
    $tc = new \TorControl\TorControl();
    $tc->connect();
    $tc->authenticate();
    $response = $tc->executeCommand('GETINFO config-text');
}
```

# Expected results

The `$response` array contains all lines of the Tor reply, without triggering an error.

# Actual results

A `ProtocolError` exception thrown by `TorControl::executeCommand()` occurs.

# Other information

I have PHPUnit test cases along with a suggested patch to fix the issue, will send the pull request in a moment.

**Comment by dunglas** [comment]
Thanks for this detailed investigation and the fix!
